### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by crepererum** [malor/cpython-lldb#15]
If you try to build the current master, all backtrace tests just break. See https://github.com/crepererum/cpython-lldb/runs/193202320 for example which is just a dummy commit on top of current master. Seems like some debug symbols are missing / have changed in the recently published Python images or the lldb builds are broken.

**Comment by malor** [comment]
Looks like this is caused by https://github.com/docker-library/python/commit/f82205cde8f0a5ffa276103a50d843edced67757 . I've tried building a Docker image w/o this change and the tests passed for me locally.

Will try to take a closer look at this during the weekend, but we will likely need to build a custom Docker image in Travis CI builds.

**Comment by malor** [comment]
Ok, the fix is not pretty, but the tests pass again: https://travis-ci.org/malor/cpython-lldb/builds/576481006
