### ISSUE TITLE
Advisory: How to setup a python debugging session in LLDB?

### ISSUE THREAD

**Issue by yophilav** [malor/cpython-lldb#71]
Hey cpython-lldb folks,

I'm stumble upon this repo and would like to play around with the tool. 
Is there any way I can directly load a given python script into LLDB without having to go through the c program like what you guys are doing for the test pipeline? If so, could you give me an instruction on how to do so please? I'm new to LLDB and any guideline is appreciated! 

I have tried `lldb python3 -- main.py` where main.py is
``` py
def main():
  il = 20
  ir = 22

  # ix = il + ir
  ix = add(il, ir)
  print(ix)
  return ix

def add(l, r):
  x = l + r
  return x
```
 Then in LLDB when I got 
```
(lldb) b add
Breakpoint 1: no locations (pending).
WARNING:  Unable to resolve breakpoint to any actual locations.
```

Any thoughts?

Thanks,
Bear

**Comment by malor** [comment]
Hi, @yophilav!

The main thing to remember is that when you execute commands in the LLDB prompt, you operate at the level of the CPython interpreter: function `add()` only exists in your _application_ code, but not in the _interpreter_ code, which is why the symbol name can't be found in the (CPython) binary, and why the breakpoint would never be hit if you were to run this program.

There is a way to achieve what you want, but it's somewhat involved right now... Basically, we need to find the function that CPython calls every time a function is called in the application code. Luckily for us, there is one like that called [_PyEval_EvalFrameDefault()](https://github.com/python/cpython/blob/3.10/Python/ceval.c#L1577). Its second argument `f` will be a pointer to a `PyFrameObject` value that contains all the information about the function call, including the application function name and its arguments. So, conceptually, you want to do something like:

```
$ lldb python3 -- main.py
(lldb) breakpoint set -r _PyEval_EvalFrameDefault -c '(int) strcmp(((PyFrameObject*) f)->f_code->co_name, "add") == 0'
```

i.e. to set a _conditional_ breakpoint that is only hit when `_PyEval_EvalFrameDefault()` evaluates the application function you are interested in.

Unfortunately, because CPython is typically built with the high level of compiler optimizations, LLDB is not always able to reliably locate the location of that argument `f`: the value of the pointer may be stored on the stack, or in one of the CPU registers. When the simple approach does not work, cpython-lldb [resorts](https://github.com/malor/cpython-lldb/blob/master/cpython_lldb.py#L617) to examining CPU registers one by one and tries to interpret those values as addresses to a valid `PyFrameObject` value. This is very ugly, but it works! There is no integration with breakpoints yet, though. I think I can implement something like what https://github.com/kastiglione/lldb-helpers does to address that. I'll file a feature request.

All that said, usually, this is not a problem, because for setting a breakpoint in the application code you would just use a normal Python debugger like `pdb`. LLDB is mainly useful for troubleshooting things like interpreter crashes, or when you have an application that gets stuck somewhere, and you don't know where that is. If it's the latter, then you would attach to a running process instead of setting a breakpoint, so this would not be a issue.

Finally, cpython-lldb is somewhat behind CPython, and the latest supported version is 3.10. There were many changes to how the interpreter evaluate the code in 3.11 and cpython-lldb hasn't caught up with those yet. 

I hope this helps! Let me know if you have more questions!

**Comment by malor** [comment]
> LLDB is mainly useful for troubleshooting things like interpreter crashes, or when you have an application that gets stuck somewhere, and you don't know where that is. If it's the latter, then you would attach to a running process instead of setting a breakpoint, so this would not be a issue.

To give you an example. Imagine, if you were trying to debug a problem that hangs somewhere. I'll modify the code snippet you attached to simulate a case like that:

```python
def main():
  il = 20
  ir = 22

  # ix = il + ir
  ix = add(il, ir)
  print(ix)
  return ix

def add(l, r):
  # simulate stuckness: you run the program, and it just hangs somewhere
  import time
  time.sleep(60)

  x = l + r
  return x

if __name__ == '__main__':
  main()
```

You can then use LLDB to attach to a running process and figure out what _application_ code is being executed right now:

```
root@93b6f9ddf479:/# python3 /opt/test/test.py
^Z
[1]+  Stopped                 python3 /opt/test/test.py
root@93b6f9ddf479:/# ps -ef | grep python3
root        1081       1  0 07:54 pts/0    00:00:00 python3 /opt/test/test.py
root        1083       1  0 07:54 pts/0    00:00:00 grep python3
root@93b6f9ddf479:/# lldb -p 1081
(lldb) process attach --pid 1081
Process 1081 stopped
* thread #1, name = 'python3', stop reason = signal SIGSTOP
    frame #0: 0x00007344da71de76 libc.so.6`__select + 22
libc.so.6`__select:
->  0x7344da71de76 <+22>: cmpq   $-0x1000, %rax            ; imm = 0xF000
    0x7344da71de7c <+28>: ja     0x7344da71dee0            ; <+128>
    0x7344da71de7e <+30>: retq
    0x7344da71de7f <+31>: nop

Executable module set to "/usr/local/bin/python3.10".
Architecture set to: x86_64-pc-linux-gnu.
(lldb) py-bt
Traceback (most recent call last):
  File "/opt/test/test.py", line 21, in <module>
    main()
  File "/opt/test/test.py", line 6, in main
    ix = add(il, ir)
  File "/opt/test/test.py", line 14, in add
    time.sleep(60)
```

**Comment by yophilav** [comment]
@malor Thank you so much for your insight. Let me digest and play around with the setup. :)
